// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzocccriolrvqiyuyjsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6b2NjY3Jpb2xydnFpeXV5anN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTQ3NTIsImV4cCI6MjA3MTMzMDc1Mn0.J4Aq6AqqgMok6uO9oJ4GDLl26KE8411Tt1ub7GT6d5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});